### PR TITLE
chore(errors): cmds to return errors instead of exiting

### PR DESCRIPTION
**Pull request by bartoszmajsak**
Instead of using `Run` and regular Cobra hooks, let's start using `RunE` and alike to return errors instead of calling `os.Exit` and let Cobra handle that instead.

This gives us the immediate benefit of better testability - as there's no `os.Exit` in the code under test, there is no risk in abruptly finishing test suite for example.

#### Open Question

As-is Cobra will print the usage of the cmd in case of failure. This can be easily disabled by setting `SilenceUsage` flag to `false`. Shall we consider that change too? @aslakknutsen

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Yeah, it's a little annoying getting cli flag help when it's a server error.

Any chance of not silence usage based on type of error, e.g. flag error is ok, 'run' error is not ?

**Comment by bartoszmajsak** [comment]
I will have a look

**Comment by bartoszmajsak** [comment]
So here's how it works. First the flags are parsed, if an error occurs, and `SilenceErrors` is set to `true`, it's printed and `--help` is suggested for a given command.

Then the actual execution happens. Here's the flow:

* if `--help` is requested - it shows it regardless
* if `SilenceErrors` is set to `true` the error is shown (that's "server" error)
* if `SilenceUsage` is set it will prompt `usage` message

So I think we are good with setting `SilenceUsage` to false. WDYT?

**Comment by aslakknutsen** [comment]
@bartoszmajsak yeah, sounds good.

**Comment by bartoszmajsak** [comment]
Done in d5cdf89

**Pull request merged**
